TownBuilding townhall1{};
townhall1.id = 0;
townhall1.type = TOWNHALL;
townhall1.buildingTime = 5;
townhall1.name = "Town Hall";
townhall1.health = 1000;
townhall1.foodCost = 0;
townhall1.woodCost = 50;
townhall1.metalCost = 0;
townhall1.orderCost = 0;
townhall1.level = 1;
townhall1.maxLevel = 3;
townBuildingDefinitions[0] = townhall1;

TownBuilding townhall2{};
townhall2.id = 1;
townhall2.type = TOWNHALL;
townhall2.buildingTime = 60;
townhall2.name = "Town Hall";
townhall2.health = 2000;
townhall2.foodCost = 0;
townhall2.woodCost = 300;
townhall2.metalCost = 0;
townhall2.orderCost = 0;
townhall2.level = 2;
townhall2.maxLevel = 3;
townBuildingDefinitions[1] = townhall2;

TownBuilding townhall3{};
townhall3.id = 2;
townhall3.type = TOWNHALL;
townhall3.buildingTime = 240;
townhall3.name = "Town Hall";
townhall3.health = 3000;
townhall3.foodCost = 0;
townhall3.woodCost = 600;
townhall3.metalCost = 0;
townhall3.orderCost = 0;
townhall3.level = 3;
townhall3.maxLevel = 3;
townBuildingDefinitions[2] = townhall3;

TownBuilding barracks1{};
barracks1.id = 3;
barracks1.type = BARRACKS;
barracks1.buildingTime = 30;
barracks1.name = "Barracks";
barracks1.health = 500;
barracks1.foodCost = 0;
barracks1.woodCost = 50;
barracks1.metalCost = 50;
barracks1.orderCost = 0;
barracks1.level = 1;
barracks1.maxLevel = 3;
townBuildingDefinitions[3] = barracks1;

TownBuilding barracks2{};
barracks2.id = 4;
barracks2.type = BARRACKS;
barracks2.buildingTime = 100;
barracks2.name = "Barracks";
barracks2.health = 1500;
barracks2.foodCost = 0;
barracks2.woodCost = 300;
barracks2.metalCost = 300;
barracks2.orderCost = 0;
barracks2.level = 2;
barracks2.maxLevel = 3;
townBuildingDefinitions[4] = barracks2;

TownBuilding barracks3{};
barracks3.id = 5;
barracks3.type = BARRACKS;
barracks3.buildingTime = 300;
barracks3.name = "Barracks";
barracks3.health = 2500;
barracks3.foodCost = 0;
barracks3.woodCost = 600;
barracks3.metalCost = 600;
barracks3.orderCost = 0;
barracks3.level = 3;
barracks3.maxLevel = 3;
townBuildingDefinitions[5] = barracks3;

TownBuilding smithy1{};
smithy1.id = 6;
smithy1.type = SMITHY;
smithy1.buildingTime = 5;
smithy1.name = "Smithy";
smithy1.health = 1000;
smithy1.foodCost = 0;
smithy1.woodCost = 200;
smithy1.metalCost = 0;
smithy1.orderCost = 0;
smithy1.level = 1;
smithy1.maxLevel = 3;
townBuildingDefinitions[6] = smithy1;

TownBuilding smithy2{};
smithy2.id = 7;
smithy2.type = SMITHY;
smithy2.buildingTime = 60;
smithy2.name = "Smithy";
smithy2.health = 2000;
smithy2.foodCost = 0;
smithy2.woodCost = 600;
smithy2.metalCost = 0;
smithy2.orderCost = 0;
smithy2.level = 2;
smithy2.maxLevel = 3;
townBuildingDefinitions[7] = smithy2;

TownBuilding smithy3{};
smithy3.id = 8;
smithy3.type = SMITHY;
smithy3.buildingTime = 240;
smithy3.name = "Smithy";
smithy3.health = 3000;
smithy3.foodCost = 0;
smithy3.woodCost = 1200;
smithy3.metalCost = 0;
smithy3.orderCost = 0;
smithy3.level = 3;
smithy3.maxLevel = 3;
townBuildingDefinitions[8] = smithy3;

TownBuilding academy1{};
academy1.id = 9;
academy1.type = ACADEMY;
academy1.buildingTime = 5;
academy1.name = "Academy";
academy1.health = 750;
academy1.foodCost = 0;
academy1.woodCost = 200;
academy1.metalCost = 100;
academy1.orderCost = 0;
academy1.level = 1;
academy1.maxLevel = 3;
townBuildingDefinitions[9] = academy1;

TownBuilding academy2{};
academy2.id = 10;
academy2.type = ACADEMY;
academy2.buildingTime = 60;
academy2.name = "Academy";
academy2.health = 1750;
academy2.foodCost = 0;
academy2.woodCost = 400;
academy2.metalCost = 200;
academy2.orderCost = 0;
academy2.level = 2;
academy2.maxLevel = 3;
townBuildingDefinitions[10] = academy2;

TownBuilding academy3{};
academy3.id = 11;
academy3.type = ACADEMY;
academy3.buildingTime = 240;
academy3.name = "Academy";
academy3.health = 2750;
academy3.foodCost = 0;
academy3.woodCost = 800;
academy3.metalCost = 500;
academy3.orderCost = 0;
academy3.level = 3;
academy3.maxLevel = 3;
townBuildingDefinitions[11] = academy3;

TownBuilding temple1{};
temple1.id = 12;
temple1.type = TEMPLE;
temple1.buildingTime = 5;
temple1.name = "Temple";
temple1.health = 400;
temple1.foodCost = 0;
temple1.woodCost = 200;
temple1.metalCost = 0;
temple1.orderCost = 0;
temple1.level = 1;
temple1.maxLevel = 3;
townBuildingDefinitions[12] = temple1;

TownBuilding temple2{};
temple2.id = 13;
temple2.type = TEMPLE;
temple2.buildingTime = 60;
temple2.name = "Temple";
temple2.health = 800;
temple2.foodCost = 0;
temple2.woodCost = 500;
temple2.metalCost = 0;
temple2.orderCost = 0;
temple2.level = 2;
temple2.maxLevel = 3;
townBuildingDefinitions[13] = temple2;

TownBuilding temple3{};
temple3.id = 14;
temple3.type = TEMPLE;
temple3.buildingTime = 190;
temple3.name = "Temple";
temple3.health = 1200;
temple3.foodCost = 0;
temple3.woodCost = 1000;
temple3.metalCost = 0;
temple3.orderCost = 0;
temple3.level = 3;
temple3.maxLevel = 3;
townBuildingDefinitions[14] = temple3;

TownBuilding workshop1{};
workshop1.id = 15;
workshop1.type = WORKSHOP;
workshop1.buildingTime = 5;
workshop1.name = "Workshop";
workshop1.health = 1100;
workshop1.foodCost = 0;
workshop1.woodCost = 200;
workshop1.metalCost = 0;
workshop1.orderCost = 0;
workshop1.level = 1;
workshop1.maxLevel = 3;
townBuildingDefinitions[15] = workshop1;

TownBuilding workshop2{};
workshop2.id = 16;
workshop2.type = WORKSHOP;
workshop2.buildingTime = 50;
workshop2.name = "Workshop";
workshop2.health = 2200;
workshop2.foodCost = 0;
workshop2.woodCost = 500;
workshop2.metalCost = 0;
workshop2.orderCost = 0;
workshop2.level = 2;
workshop2.maxLevel = 3;
townBuildingDefinitions[16] = workshop2;

TownBuilding workshop3{};
workshop3.id = 17;
workshop3.type = WORKSHOP;
workshop3.buildingTime = 250;
workshop3.name = "Workshop";
workshop3.health = 3300;
workshop3.foodCost = 0;
workshop3.woodCost = 1000;
workshop3.metalCost = 0;
workshop3.orderCost = 0;
workshop3.level = 3;
workshop3.maxLevel = 3;
townBuildingDefinitions[17] = workshop3;

TownBuilding warehouse1{};
warehouse1.id = 18;
warehouse1.type = WAREHOUSE;
warehouse1.buildingTime = 5;
warehouse1.name = "Warehouse";
warehouse1.health = 1600;
warehouse1.foodCost = 0;
warehouse1.woodCost = 10;
warehouse1.metalCost = 0;
warehouse1.orderCost = 0;
warehouse1.level = 1;
warehouse1.maxLevel = 3;
townBuildingDefinitions[18] = warehouse1;

TownBuilding warehouse2{};
warehouse2.id = 19;
warehouse2.type = WAREHOUSE;
warehouse2.buildingTime = 55;
warehouse2.name = "Warehouse";
warehouse2.health = 2400;
warehouse2.foodCost = 0;
warehouse2.woodCost = 800;
warehouse2.metalCost = 0;
warehouse2.orderCost = 0;
warehouse2.level = 2;
warehouse2.maxLevel = 3;
townBuildingDefinitions[19] = warehouse2;

TownBuilding warehouse3{};
warehouse3.id = 20;
warehouse3.type = WAREHOUSE;
warehouse3.buildingTime = 185;
warehouse3.name = "Warehouse";
warehouse3.health = 3600;
warehouse3.foodCost = 0;
warehouse3.woodCost = 2000;
warehouse3.metalCost = 0;
warehouse3.orderCost = 0;
warehouse3.level = 3;
warehouse3.maxLevel = 3;
townBuildingDefinitions[20] = warehouse3;

TownBuilding marketplace1{};
marketplace1.id = 24;
marketplace1.type = MARKETPLACE;
marketplace1.buildingTime = 5;
marketplace1.name = "Marketplace";
marketplace1.health = 500;
marketplace1.foodCost = 200;
marketplace1.woodCost = 200;
marketplace1.metalCost = 200;
marketplace1.orderCost = 0;
marketplace1.level = 1;
marketplace1.maxLevel = 3;
townBuildingDefinitions[24] = marketplace1;

TownBuilding marketplace2{};
marketplace2.id = 25;
marketplace2.type = MARKETPLACE;
marketplace2.buildingTime = 70;
marketplace2.name = "Marketplace";
marketplace2.health = 1000;
marketplace2.foodCost = 400;
marketplace2.woodCost = 400;
marketplace2.metalCost = 400;
marketplace2.orderCost = 0;
marketplace2.level = 2;
marketplace2.maxLevel = 3;
townBuildingDefinitions[25] = marketplace2;

TownBuilding marketplace3{};
marketplace3.id = 26;
marketplace3.type = MARKETPLACE;
marketplace3.buildingTime = 130;
marketplace3.name = "Marketplace";
marketplace3.health = 1500;
marketplace3.foodCost = 1000;
marketplace3.woodCost = 1000;
marketplace3.metalCost = 1000;
marketplace3.orderCost = 0;
marketplace3.level = 3;
marketplace3.maxLevel = 3;
townBuildingDefinitions[26] = marketplace3;

TownBuilding wall0{};
wall0.id = 27;
wall0.type = WALL;
wall0.buildingTime = 0;
wall0.name = "Wall";
wall0.health = 5000;
wall0.foodCost = 0;
wall0.woodCost = 0;
wall0.metalCost = 0;
wall0.orderCost = 0;
wall0.level = 0;
wall0.maxLevel = 3;
townBuildingDefinitions[27] = wall0;

TownBuilding wall1{};
wall1.id = 28;
wall1.type = WALL;
wall1.buildingTime = 300;
wall1.name = "Wall";
wall1.health = 10000;
wall1.foodCost = 0;
wall1.woodCost = 500;
wall1.metalCost = 100;
wall1.orderCost = 0;
wall1.level = 1;
wall1.maxLevel = 3;
townBuildingDefinitions[28] = wall1;

TownBuilding wall2{};
wall2.id = 29;
wall2.type = WALL;
wall2.buildingTime = 3000;
wall2.name = "Wall";
wall2.health = 20000;
wall2.foodCost = 0;
wall2.woodCost = 1200;
wall2.metalCost = 500;
wall2.orderCost = 0;
wall2.level = 2;
wall2.maxLevel = 3;
townBuildingDefinitions[29] = wall2;

